- src/main/java/org/codinjutsu/tools/jenkins/JenkinsSettings.java
- src/main/java/org/codinjutsu/tools/jenkins/logic/RequestManager.java
- src/main/java/org/codinjutsu/tools/jenkins/logic/RequestManagerInterface.java
- src/main/java/org/codinjutsu/tools/jenkins/security/BasicSecurityClient.java
- src/main/java/org/codinjutsu/tools/jenkins/security/DefaultSecurityClient.java
- src/main/java/org/codinjutsu/tools/jenkins/security/JenkinsVersion.java
- src/main/java/org/codinjutsu/tools/jenkins/security/SecurityClientFactory.java
- src/main/java/org/codinjutsu/tools/jenkins/view/ConfigurationPanel.form
- src/main/java/org/codinjutsu/tools/jenkins/view/ConfigurationPanel.java
Modified ConfigurationPanel
Added JenkinsVersion enum
Changed RequestManagerInterface.authenticate method singature - added JenkinsVersion parameter
Adapt Security package and JenkinsSettings, with changes
> support for version 2.x

- src/main/java/org/codinjutsu/tools/jenkins/model/BuildStatusEnum.java
Fix NPE in BuildStatusEnum
dboissier/jenkins-control-plugin#143
> Fix NPE in BuildStatusEnum

- src/main/java/org/codinjutsu/tools/jenkins/logic/RequestManager.java
- src/test/java/org/codinjutsu/tools/jenkins/logic/RequestManagerTest.java
Fix for Issue #172 
remove constructor with non-injectable parameter
> Fix Issue 172

- src/main/java/org/codinjutsu/tools/jenkins/view/ConfigurationPanel.form
> Fix issue 163 (spelling error in config form)

- src/main/java/org/codinjutsu/tools/jenkins/logic/JenkinsJsonParser.java
- src/main/java/org/codinjutsu/tools/jenkins/logic/JenkinsParser.java
- src/main/java/org/codinjutsu/tools/jenkins/logic/UrlBuilder.java
- src/main/java/org/codinjutsu/tools/jenkins/model/JobParameter.java
- src/main/java/org/codinjutsu/tools/jenkins/view/BuildParamDialog.java
I added two features:
- Add description text in build param dialog
- Build param dialog centered display
like this
> Add description text in build param dialog

- src/main/java/org/codinjutsu/tools/jenkins/JenkinsAppSettings.java
- src/main/java/org/codinjutsu/tools/jenkins/JobTracker.java
- src/main/java/org/codinjutsu/tools/jenkins/TraceableBuildJob.java
- src/main/java/org/codinjutsu/tools/jenkins/TraceableBuildJobFactory.java
- src/main/java/org/codinjutsu/tools/jenkins/logic/RssLogic.java
- src/main/java/org/codinjutsu/tools/jenkins/view/BuildParamDialog.java
- src/main/java/org/codinjutsu/tools/jenkins/view/ConfigurationPanel.form
- src/main/java/org/codinjutsu/tools/jenkins/view/ConfigurationPanel.java
> Merge PR #161: Add Retry Failed Builds

- CHANGELOG.txt
- README.md
- build.gradle
- includes/pluginChanges.html
- src/main/java/org/codinjutsu/tools/jenkins/logic/RequestManager.java
- src/main/java/org/codinjutsu/tools/jenkins/view/BuildParamDialog.java
- src/main/java/org/codinjutsu/tools/jenkins/view/action/ShowLogAction.java
- src/main/java/org/codinjutsu/tools/jenkins/view/parameter/HiddenParameterRenderer.java
- src/main/java/org/codinjutsu/tools/jenkins/view/parameter/JobParameterComponent.java
- src/main/resources/META-INF/JobParameterRenderer.xml
- src/test/java/org/codinjutsu/tools/jenkins/view/parameter/BuiltInJobParameterRendererTest.java
- src/test/java/org/codinjutsu/tools/jenkins/view/parameter/HiddenParameterRendererTest.java
- src/test/java/org/codinjutsu/tools/jenkins/view/parameter/JobParameterTest.java
- src/test/java/org/codinjutsu/tools/jenkins/view/parameter/NodeParameterRendererTest.java
- src/test/java/org/codinjutsu/tools/jenkins/view/parameter/SeparatorRendererTest.java
fixes #219 How to run a jenkins job with hidden fields?
fixes #218 "Show log" on Job without Build leads to error
> Merge #218 + #219

- CHANGELOG.txt
- README.md
- build.gradle
- includes/pluginChanges.html
- src/main/java/org/codinjutsu/tools/jenkins/exception/NoJobFoundException.java
- src/main/java/org/codinjutsu/tools/jenkins/logic/RequestManager.java
- src/main/java/org/codinjutsu/tools/jenkins/security/BasicSecurityClient.java
use Idea Server Certificates and Proxy Settings
remove libs which are provided by Idea Platform
> solves #217 Show Log not possible for selected Job if self-signed or invalid SSL certificate is used

- CHANGELOG.txt
- includes/pluginChanges.html
- src/main/java/org/codinjutsu/tools/jenkins/logic/BrowserPanelAuthenticationHandler.java
- src/main/java/org/codinjutsu/tools/jenkins/logic/ConfigurationValidator.java
- src/main/java/org/codinjutsu/tools/jenkins/logic/JenkinsJsonParser.java
- src/main/java/org/codinjutsu/tools/jenkins/logic/JenkinsParser.java
- src/main/java/org/codinjutsu/tools/jenkins/logic/RequestManager.java
- src/main/java/org/codinjutsu/tools/jenkins/logic/RequestManagerInterface.java
- src/main/java/org/codinjutsu/tools/jenkins/logic/UrlBuilder.java
- src/main/java/org/codinjutsu/tools/jenkins/model/Jenkins.java
- src/main/java/org/codinjutsu/tools/jenkins/security/AuthenticationException.java
- src/main/java/org/codinjutsu/tools/jenkins/security/BasicSecurityClient.java
- src/main/java/org/codinjutsu/tools/jenkins/security/DefaultSecurityClient.java
- src/main/java/org/codinjutsu/tools/jenkins/security/SecurityClient.java
- src/main/java/org/codinjutsu/tools/jenkins/view/BrowserPanel.java
- src/main/java/org/codinjutsu/tools/jenkins/view/ConfigurationPanel.java
- src/test/java/org/codinjutsu/tools/jenkins/logic/ConfigurationValidatorTest.java
- src/test/java/org/codinjutsu/tools/jenkins/logic/JenkinsJsonParserTest.java
- src/test/java/org/codinjutsu/tools/jenkins/logic/RequestManagerTest.java
- src/test/java/org/codinjutsu/tools/jenkins/logic/UrlBuilderTest.java
- src/test/resources/org/codinjutsu/tools/jenkins/logic/JsonRequestManager_loadJenkinsWorkspaceWithIncorrectHostInTheResponse.json
* improved validation
* "Test Connection" uses Validation
* Refresh View if new setting is applied
> Fix: #227 Jenkins invalid configuration causes AuthenticationException and UI not respond correctly to this

- CHANGELOG.txt
- build.gradle
- includes/pluginChanges.html
- src/main/java/org/codinjutsu/tools/jenkins/logic/JenkinsJsonParser.java
- src/main/java/org/codinjutsu/tools/jenkins/logic/JenkinsParser.java
- src/main/java/org/codinjutsu/tools/jenkins/logic/RequestManager.java
- src/main/java/org/codinjutsu/tools/jenkins/logic/RequestManagerInterface.java
- src/main/java/org/codinjutsu/tools/jenkins/logic/UrlBuilder.java
- src/main/java/org/codinjutsu/tools/jenkins/model/BuildType.java
- src/main/java/org/codinjutsu/tools/jenkins/model/Job.java
- src/main/java/org/codinjutsu/tools/jenkins/view/BrowserPanel.java
- src/main/java/org/codinjutsu/tools/jenkins/view/action/ShowLogAction.java
- src/test/java/org/codinjutsu/tools/jenkins/logic/JenkinsJsonParserTest.java
- src/test/java/org/codinjutsu/tools/jenkins/logic/JobBuilder.java
- src/test/java/org/codinjutsu/tools/jenkins/logic/RequestManagerTest.java
- src/test/java/org/codinjutsu/tools/jenkins/logic/UrlBuilderTest.java
- src/test/java/org/codinjutsu/tools/jenkins/view/action/ShowLogActionTest.java
- src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker
- src/test/resources/org/codinjutsu/tools/jenkins/logic/JsonRequestManager_loadJobWithAllLastBuilds.json
- src/test/resources/org/codinjutsu/tools/jenkins/logic/JsonRequestManager_loadJobWithLastFailedBuildIsNull.json
close #197 Show log for individual builds of selected jobs
Add additional "Show Log" entries to context menu
> close #197 Show log for individual builds of selected jobs

- CHANGELOG.txt
- build.gradle
- includes/pluginChanges.html
- src/main/java/org/codinjutsu/tools/jenkins/logic/JenkinsJsonParser.java
- src/main/java/org/codinjutsu/tools/jenkins/logic/JenkinsParser.java
- src/main/java/org/codinjutsu/tools/jenkins/logic/RequestManager.java
- src/main/java/org/codinjutsu/tools/jenkins/logic/RequestManagerInterface.java
- src/main/java/org/codinjutsu/tools/jenkins/util/GuiUtil.java
- src/main/java/org/codinjutsu/tools/jenkins/view/BrowserPanel.java
- src/main/java/org/codinjutsu/tools/jenkins/view/action/ActionUtil.java
- src/main/java/org/codinjutsu/tools/jenkins/view/action/LogToolWindow.java
- src/main/java/org/codinjutsu/tools/jenkins/view/action/LogToolWindowFactory.java
- src/main/java/org/codinjutsu/tools/jenkins/view/action/RunBuildAction.java
- src/main/java/org/codinjutsu/tools/jenkins/view/action/ShowLogAction.java
- src/main/java/org/codinjutsu/tools/jenkins/view/action/results/JobTestConsoleProperties.java
- src/main/java/org/codinjutsu/tools/jenkins/view/action/results/JobTestResultsToolWindow.java
- src/main/java/org/codinjutsu/tools/jenkins/view/action/results/JobTestResultsToolWindowFactory.java
- src/main/resources/META-INF/plugin.xml
- src/test/java/org/codinjutsu/tools/jenkins/logic/RequestManagerTest.java
- src/test/java/org/codinjutsu/tools/jenkins/view/action/LogToolWindowTest.java
- src/test/java/org/codinjutsu/tools/jenkins/view/action/ShowLogActionTest.java
resolve #253 
* Show last log also for running builds
* Show last log after trigger build. Only check if new Build number exists and build is running. Queued jobs are not open log
> Feature Request  #253: Log in progress

- CHANGELOG.txt
- build.gradle
- includes/pluginChanges.html
- src/main/java/org/codinjutsu/tools/jenkins/JenkinsWindowManager.java
- src/main/java/org/codinjutsu/tools/jenkins/StartupJenkinsService.java
- src/main/java/org/codinjutsu/tools/jenkins/WatchedJobsDecorator.java
- src/main/java/org/codinjutsu/tools/jenkins/logic/BrowserPanelAuthenticationHandler.java
- src/main/java/org/codinjutsu/tools/jenkins/logic/ExecutorService.java
- src/main/java/org/codinjutsu/tools/jenkins/logic/LoginService.java
- src/main/java/org/codinjutsu/tools/jenkins/logic/RequestManager.java
- src/main/java/org/codinjutsu/tools/jenkins/logic/RssAuthenticationActionHandler.java
- src/main/resources/META-INF/plugin.xml
resolve #181 Change to Dynamic Plugin for >=2020.3
> Dynamic Plugin for 2020.3

- CHANGELOG.txt
- build.gradle
- includes/pluginChanges.html
- src/main/java/org/codinjutsu/tools/jenkins/view/parameter/ExtendedChoiceParameterRenderer.java
- src/main/resources/META-INF/JobParameterRenderer.xml
- src/test/java/org/codinjutsu/tools/jenkins/view/parameter/ExtendedChoiceParameterRendererTest.java
> #240 PT_MULTI_SELECT and PT_CHECKBOX not supported

- CHANGELOG.md
- build.gradle
- gradle/wrapper/gradle-wrapper.properties
- src/main/java/org/codinjutsu/tools/jenkins/logic/JenkinsJsonParser.java
- src/test/java/org/codinjutsu/tools/jenkins/logic/JenkinsJsonParserTest.java
- src/test/resources/org/codinjutsu/tools/jenkins/logic/JsonRequestManager_jobWithNullAction.json
> fixes #297 NPE for Empty Build Actions

- .travis.yml
- CHANGELOG.md
- src/main/java/org/codinjutsu/tools/jenkins/DoubleClickAction.java
- src/main/java/org/codinjutsu/tools/jenkins/JenkinsAppSettings.java
- src/main/java/org/codinjutsu/tools/jenkins/JenkinsTree.java
- src/main/java/org/codinjutsu/tools/jenkins/JenkinsWindowManager.java
- src/main/java/org/codinjutsu/tools/jenkins/view/BrowserPanel.java
- src/main/java/org/codinjutsu/tools/jenkins/view/ConfigurationPanel.form
- src/main/java/org/codinjutsu/tools/jenkins/view/ConfigurationPanel.java
- src/main/java/org/codinjutsu/tools/jenkins/view/DoubleClickActionRenderer.java
- src/main/java/org/codinjutsu/tools/jenkins/view/JobClickHandler.java
- src/main/java/org/codinjutsu/tools/jenkins/view/action/JobAction.java
- src/main/java/org/codinjutsu/tools/jenkins/view/action/JobActions.java
- src/main/java/org/codinjutsu/tools/jenkins/view/action/LoadBuildsAction.java
- src/main/java/org/codinjutsu/tools/jenkins/view/action/RunBuildAction.java
- src/main/java/org/codinjutsu/tools/jenkins/view/action/ShowLogAction.java
- src/test/java/org/codinjutsu/tools/jenkins/view/DoubleClickActionRendererTest.java
> Implement double click actions

- src/main/java/org/codinjutsu/tools/jenkins/view/ConfigurationPanel.form
- src/main/java/org/codinjutsu/tools/jenkins/view/ConfigurationPanel.java
> Please rename password label to "Password/API Token"

- src/main/java/org/codinjutsu/tools/jenkins/logic/RequestManager.java
- src/main/java/org/codinjutsu/tools/jenkins/view/action/LogToolWindow.java
> Log streaming should cancelable

- CHANGELOG.md
- build.gradle
- gradle.properties
- src/main/java/org/codinjutsu/tools/jenkins/logic/UrlBuilder.java
- src/main/java/org/codinjutsu/tools/jenkins/model/VirtualFilePart.java
- src/main/java/org/codinjutsu/tools/jenkins/security/BasicSecurityClient.java
- src/main/java/org/codinjutsu/tools/jenkins/security/DefaultSecurityClient.java
- src/test/java/org/codinjutsu/tools/jenkins/logic/UrlBuilderTest.java
- src/test/java/org/codinjutsu/tools/jenkins/security/DefaultSecurityClientTest.java
> use newer httpclient to support 2022.3

- CHANGELOG.md
- gradle.properties
- src/main/java/org/codinjutsu/tools/jenkins/logic/BrowserPanelAuthenticationHandler.java
- src/main/java/org/codinjutsu/tools/jenkins/util/GuiUtil.java
- src/main/java/org/codinjutsu/tools/jenkins/view/BrowserPanel.java
closes #413 0.13.15-2022.2 - still not working with Intellij 2022.3
> force more methods to run in EDT

- CHANGELOG.md
- gradle.properties
- src/main/java/org/codinjutsu/tools/jenkins/logic/RequestManager.java
- src/main/java/org/codinjutsu/tools/jenkins/security/DefaultSecurityClient.java
> fix proxy handling

- CHANGELOG.md
- src/main/java/org/codinjutsu/tools/jenkins/logic/UrlBuilder.java
> [bug report]java.lang.IllegalArgumentException: URL is malformed

- CHANGELOG.md
- gradle.properties
- src/main/java/org/codinjutsu/tools/jenkins/view/BuildParamDialog.java
> Parameters window too big for screen

- CHANGELOG.md
- build.gradle
- src/main/java/org/codinjutsu/tools/jenkins/exception/NoBuildFoundException.java
- src/main/java/org/codinjutsu/tools/jenkins/logic/RequestManager.java
- src/main/java/org/codinjutsu/tools/jenkins/logic/RequestManagerInterface.java
- src/main/java/org/codinjutsu/tools/jenkins/model/Build.java
- src/main/java/org/codinjutsu/tools/jenkins/view/BrowserPanel.java
- src/main/java/org/codinjutsu/tools/jenkins/view/action/GotoAllureReportPageAction.java
- src/main/java/org/codinjutsu/tools/jenkins/view/action/GotoBuildConsolePageAction.java
- src/main/java/org/codinjutsu/tools/jenkins/view/action/GotoBuildPageAction.java
- src/main/java/org/codinjutsu/tools/jenkins/view/action/GotoBuildTestResultsPageAction.java
- src/main/java/org/codinjutsu/tools/jenkins/view/action/LogToolWindow.java
- src/main/java/org/codinjutsu/tools/jenkins/view/action/ShowBuildLogAction.java
- src/main/java/org/codinjutsu/tools/jenkins/view/action/StopBuildAction.java
- src/test/java/org/codinjutsu/tools/jenkins/logic/RequestManagerTest.java
> Show log of a selected build

- CHANGELOG.md
- gradle.properties
- src/main/java/org/codinjutsu/tools/jenkins/logic/JenkinsClient.java
- src/main/java/org/codinjutsu/tools/jenkins/logic/JenkinsNotifier.java
- src/main/java/org/codinjutsu/tools/jenkins/logic/RequestManager.java
- src/main/java/org/codinjutsu/tools/jenkins/security/BasicSecurityClient.java
- src/main/java/org/codinjutsu/tools/jenkins/security/DefaultSecurityClient.java
- src/main/java/org/codinjutsu/tools/jenkins/security/JenkinsPost.java
- src/main/java/org/codinjutsu/tools/jenkins/security/JenkinsRedirectStrategy.java
- src/main/java/org/codinjutsu/tools/jenkins/security/SecurityClient.java
- src/main/java/org/codinjutsu/tools/jenkins/view/action/RunBuildAction.java
> use same http client for JenkinsHttpClient an SecurityClient

- gradle.properties
- src/main/java/org/codinjutsu/tools/jenkins/security/DefaultSecurityClient.java
- src/main/java/org/codinjutsu/tools/jenkins/security/JenkinsConnectionSocketFactory.java
- src/main/java/org/codinjutsu/tools/jenkins/security/JenkinsDnsResolver.java
> Add SOCKS Proxy Support

- CHANGELOG.md
- src/main/java/org/codinjutsu/tools/jenkins/view/BuildParamDialog.form
> Wrap content in a JScrollPane

- src/main/java/org/codinjutsu/tools/jenkins/view/extension/JobParameterRenderers.java
- src/main/java/org/codinjutsu/tools/jenkins/view/inputfilter/HintTextField.java
- src/main/java/org/codinjutsu/tools/jenkins/view/inputfilter/InputFilterList.java
- src/main/java/org/codinjutsu/tools/jenkins/view/parameter/BuiltInJobParameterRenderer.java
- src/main/java/org/codinjutsu/tools/jenkins/view/parameter/GitParameterRenderer.java
Improves usability and navigation for scenarios with a large number of choices.
- Implemented a new JComponent, InputFilterList, to enable search functionality.
- Applied InputFilterList in the following cases:
- When Built-in Job type has more than 10 choices.
- For Git Parameter type.
Fixes #656
> Add InputFilterList for Improved Searchability

- src/test/java/org/codinjutsu/tools/jenkins/view/parameter/BuiltInJobParameterRendererTest.java
- src/test/java/org/codinjutsu/tools/jenkins/view/parameter/GitParameterRendererTest.java
- src/test/java/org/codinjutsu/tools/jenkins/view/parameter/ListGitBranchesParameterRendererTest.java
- Modified test cases that were failing due to the introduction of InputFilterList.
- Ensured test cases reflect the updated behavior and functionality.
- Verified all tests pass to maintain code integrity and functionality.
Related to PR #657
> Fix Broken Test Cases for InputFilterList Implementation
